import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	// openGraph: {
	//   title: "MakeMyReadMe",
	//   description: "Generate stunning README files with MakeMyReadMe.",
	//   images: [
	//     {
	//       url: "https://makemyREADME.com/images/og-image.png",
	//       width: 1200,
	//       height: 630,
	//     },
	//   ],
	//   url: "https://makemyREADME.com",
	//   site_name: "MakeMyReadMe",
	//   type: "website",
	// },
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Navbar />
				<main className=" sm:overflow-x-hidden">{children}</main>
				<Footer />
				<ToastContainer
					position="top-right"
					autoClose={3000}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme="light"
					style={{
						width: "500px",
						color: "black",
						fontWeight: "bold",
					}}
				/>
			</body>
		</html>
	);
}
